# Generated by Django 5.2.4 on 2025-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('professional', 'Professional'), ('education', 'Education'), ('lifestyle', 'Lifestyle & Social'), ('sports', 'Sports & Fitness'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
